parameters:
    profile_photos_directory: '%kernel.project_dir%/public/uploads/profiles'    
    activites_images_directory: '%kernel.project_dir%/public/uploads/activites'
    evenements_images_directory: '%kernel.project_dir%/public/uploads/evenements'
    cities_json_path: '%kernel.project_dir%/data/cities.json'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\CityCountryLookupService:
        arguments:
            $citiesJsonPath: '%cities_json_path%'
            $restCountriesService: '@App\Service\RestCountriesService'

    App\Service\HebergementScraperService:
        arguments:
            $rapidApiKey: '%env(RAPIDAPI_KEY)%'
            $rapidApiHost: '%env(RAPIDAPI_HOST)%'
            $rapidApiUrl: '%env(RAPIDAPI_URL)%'
            $rapidApiCurrency: '%env(RAPIDAPI_CURRENCY)%'
            $rapidApiLanguage: '%env(RAPIDAPI_LANGUAGE)%'

    App\Service\UnsplashImageService:
        arguments:
            $accessKey: '%env(UNSPLASH_ACCESS_KEY)%'

    App\Service\DestinationImageFetcherService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\YouTubeVideoService:
        arguments:
            $apiKey: '%env(YOUTUBE_API_KEY)%'
            $minDurationSeconds: 30
            $maxDurationSeconds: 240